name: Build Image
on:
  watch:
    types: [ started ]
    
jobs:
  build:
      runs-on: ubuntu-latest
      name: Build image job
      steps:
          - name: Checkout master
            uses: actions/checkout@master
          - name: Build and publish image
            uses: ilteoood/docker_buildx@master
            with:
              publish: true
              imageName: 54ik1/php-v8js
              platform: linux/amd64,linux/arm64 #,linux/arm/v7,linux/arm64/v8,linux/mips64le
              tag: dev 
              dockerHubUser: ${{ secrets.USERNAME }} 
              dockerHubPassword: ${{ secrets.PASSWORD }} 
