
name: BUILD PHP V8JS

on:
  workflow_dispatch:
  schedule: 
    - cron: '10 6 * * *' 

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build Php-v8js
      run: |
        sudo docker build -t 54ik1/php-v8js:dev .
    
    - name: Push DockerHub
      run: |
        sudo docker login --username="${{ secrets.USERNAME }}" --password="${{ secrets.PASSWORD }}"
        sudo docker push 54ik1/php-v8js:dev
