
name: build

on:
  push: # push触发
    branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '10 6 * * *' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时,如上表示每天14点10分

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build Php-v8js
      run: |
        sudo docker build -t 54ik1/php-v8js:dev .
    
    - name: Push DockerHub
      run: |
        sudo docker login --username="${{ secrets.USERNAME }}" --password="${{ secrets.PASSWORD }}"
        sudo docker push 54ik1/php-v8js:dev
